# P ASSIGMENT 2

## Normalization Problem

In [1]:
import numpy as np

In [2]:
X = np.random.rand(5, 5)
print("Original array: ")
print(X) #create a randomized array

Original array: 
[[0.62258683 0.07785994 0.34469463 0.74861046 0.92254345]
 [0.41976873 0.44031221 0.01014255 0.99958244 0.46738464]
 [0.7350112  0.35333766 0.58121538 0.70185447 0.75089785]
 [0.05349887 0.05649226 0.50249404 0.76007761 0.89512677]
 [0.26211528 0.91548422 0.42235994 0.04858943 0.45287484]]


In [3]:
mean_val = np.mean(X) #to calculate the mean of the values in the array

In [4]:
std_val = np.std(X) #to calculate the standard deviation of the values in the array

In [5]:
X_normalized = (X - mean_val) / std_val #calculate the earlier values to normal

In [6]:
np.save('X_normalized.npy', X_normalized)

In [7]:
print("Normalized array:")
print(X_normalized)

Normalized array:
[[ 0.40659944 -1.42703973 -0.52883085  0.83081544  1.41630213]
 [-0.27611924 -0.20696653 -1.65498746  1.67562789 -0.11583634]
 [ 0.78503812 -0.499737    0.26733641  0.67342721  0.83851517]
 [-1.50904306 -1.49896681  0.0023476   0.86941572  1.32401313]
 [-0.80680634  1.39253962 -0.26739679 -1.52556904 -0.16467869]]


## DIVISIBLE BY 3 PROBLEM

In [14]:
numbers = np.arange(1, 101) #makes an array of 1-100 
numbers

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
squares = numbers ** 2 #to square the values in the array

In [10]:
A = squares.reshape(10, 10) #reshape the current array into a 10x10 matrix format

In [11]:
div_by_3 = A[A % 3 == 0] #determine the values divisible by 3 using boolean indexing

In [12]:
np.save('div_by_3.npy', div_by_3)

In [15]:
print("\nElements divisible by 3:")
print(div_by_3)


Elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
